FROM node:9

RUN mkdir /app
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends postgresql-client

RUN git clone https://github.com/cityofaustin/ctxfloods-backend
WORKDIR /app/ctxfloods-backend
COPY backend-entrypoint.sh /app/ctxfloods-backend/
RUN ls
RUN yarn

ENTRYPOINT ["./backend-entrypoint.sh"]