# AWS
export AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID_DEV_TRAVIS
export AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY_DEV_TRAVIS
export BUCKET_NAME=ctx-floods-frontend-prod-legacy-sync

# App
export REACT_APP_BACKEND_URL=$TRAVIS_BACKEND_PROD_LEGACY_SYNC
